import "./globals.css";
import { Poppins } from "next/font/google";
import { AuthProvider } from "./Provider";
const inter = Poppins({ subsets: ["latin"] , weight:['100', '200', '300', '400', '500', '600', '700', '800', '900'] });
import ContextUserData from "@/ContextUser";
import { handler } from "./api/auth/[...nextauth]/route";
export const metadata = {
  title: "Edulearn",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap"/>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <ContextUserData>

            {children}

          </ContextUserData>
        </AuthProvider>
      </body>
    </html>
  );
}
