import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "./Provider";
const inter = Inter({ subsets: ["latin"] });
import ContextUserData from "@/ContextUser";
export const metadata = {
  title: "Edulearn",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico'
  }
};

export default function RootLayout({ children }) {

  return (

    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ContextUserData>

            {children}

          </ContextUserData>
        </AuthProvider>
      </body>
    </html>
  );
}
